### ISSUE TITLE
Youtube v2 API is shutting down on April 20, 2015, migrate to v3.

### ISSUE THREAD

**Issue by MichealKenny** [cheeplusplus/groompbot#3] opened 2015-04-07 09:21 UTC
Just a friendly notice from another reddit bot creator that uses the Youtube API.

the v3 playlistItems endpoint is also painfully slow to update(20 to 40 minutes, compared to the v2 uploads endpoint which updates instantaneously) The fastest endpoint I've found is the search one, still takes between 150-250 seconds to update.

**Comment by OliPicard** [comment] 2015-04-08 18:11
Hi Micheal,

Not sure if your aware of this but Andrew did post a build using the YouTube v3 API. 
see: https://github.com/AndrewNeo/groompbot/issues/2
Thanks
Oliver

**Comment by MichealKenny** [comment] 2015-04-08 22:05
Thanks Oli, didn't see that because it was closed, I will say though, v3 is absolutely usable, it's just not as good, the 30 minutes he was referencing is with using playlistItems which I agree is useless, but with the search endpoint or the activities endpoint in v3, it updates in around 100-300 seconds, so in line with the speeds groompbot used to do.

**Comment by OliPicard** [comment] 2015-04-21 14:45
Hey Micheal,

Have you had any luck in changing the endpoints? Would love to know if you have gotten any progress as yesterday was the nail in the coffin for v2.

**Comment by MichealKenny** [comment] 2015-04-22 00:17
Nope, I've spent tens of hours researching v3 for the past few months, I almost know it inside out, it's just slow, I think the search endpoint is adequate for groompbot because it was never really fast in the first place, 100-300 seconds to update should be fine. I on the other hand like speed, a bot should be faster than a human. I have resorted to basic web scraping which takes about 3 seconds to update(v2 uploads took 2), and works good, of course with this method you run the risk of having your IP blocked because you're not using the official API. sample code:

```
from bs4 import BeautifulSoup
from requests import get

bs4_attrs = {'class': 'yt-uix-sessionlink yt-uix-tile-link  spf-link  yt-ui-ellipsis yt-ui-ellipsis-2'}
headers = {'Cache-Control': 'max-age=0, no-cache'}

html = get('https://www.youtube.com/channel/{channel_id}/videos'.format(channel_id=channel), headers=headers).text
soup = BeautifulSoup(html)
latest = soup.find_all('a', attrs=bs4_attrs)[0]

video_title = latest.string
video_id = latest.get('href').strip('/watch?v=')
```

**Comment by cheeplusplus** [comment] 2015-04-22 08:52
Am working on a solution, closing as a dupe of #2 for now

**Closed as completed** 2015-04-22 08:52 UTC
